-- ============================================================================
-- Stash — 0001_init
-- Core schema + Row Level Security for the single-user expense + resale-stock app.
--
-- IMPORTANT (automatic RLS): the Supabase project has "automatic RLS" ON, which
-- ENABLES RLS on new tables but does NOT create any policy. Without policies a
-- table is locked (no rows readable/writable). So EVERY table below defines
-- explicit policies: auth.uid() = user_id for select / insert / update / delete.
--
-- additive-only: this migration only CREATEs. No drops, no destructive changes.
-- Run in Supabase SQL Editor (as project owner).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.transaction_type as enum ('income', 'expense');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.category_kind as enum ('income', 'expense');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.wallet_type as enum ('cash', 'bank', 'promptpay');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.item_condition as enum ('new', 'used_good', 'flawed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.stock_status as enum ('in_stock', 'partial', 'sold');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();   -- now() is in pg_catalog, always resolvable
  return new;
end;
$$;

-- ===========================================================================
-- wallets
-- ===========================================================================
create table if not exists public.wallets (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name       text not null,
  type       public.wallet_type not null default 'cash',
  balance    numeric(14, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===========================================================================
-- categories
-- ===========================================================================
create table if not exists public.categories (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name              text not null,
  kind              public.category_kind not null default 'expense',
  -- true => saving in this category opens the stock-item form automatically
  is_stock_category boolean not null default false,
  icon              text,                 -- Tabler icon name
  color             text,                 -- hex or token name
  sort_order        integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ===========================================================================
-- stock_items  (created before transactions add their cross-FK below)
-- ===========================================================================
create table if not exists public.stock_items (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name                  text not null,
  category              text,             -- free-text type (เสื้อ/รองเท้า/...)
  brand                 text,
  size                  text,
  color                 text,
  condition             public.item_condition,
  cost_per_unit         numeric(14, 2) not null default 0,   -- from the source expense
  qty_total             integer not null default 1 check (qty_total >= 0),
  qty_remaining         integer not null default 1 check (qty_remaining >= 0),
  target_price          numeric(14, 2),
  sku                   text,             -- auto-generated by the app, e.g. STZ-NIK-0042
  status                public.stock_status not null default 'in_stock',
  needs_details         boolean not null default false,       -- true = "รอเติมรายละเอียด"
  photos                text[] not null default '{}',
  -- the expense transaction that created this item (set after transactions exists)
  source_transaction_id uuid,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint stock_qty_remaining_le_total check (qty_remaining <= qty_total)
);

-- ===========================================================================
-- transactions
-- ===========================================================================
create table if not exists public.transactions (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type              public.transaction_type not null,
  amount            numeric(14, 2) not null check (amount >= 0),
  -- RESTRICT (ledger integrity): a category/wallet that still has transactions
  -- cannot be deleted. This protects historical spending-by-category and
  -- per-wallet balance reports from silently losing their grouping. The app is
  -- expected to offer a "merge / reassign then delete" flow in settings.
  category_id       uuid references public.categories (id) on delete restrict,
  wallet_id         uuid references public.wallets (id) on delete restrict,
  date              date not null default current_date,
  note              text,
  -- true => this expense is a stock purchase. Per the chosen accounting model,
  -- stock purchases are treated as INVENTORY (an asset), so spending charts and
  -- budgets should EXCLUDE rows where is_stock_purchase = true. Profit is
  -- recognised later at sale time via stock_sales.
  is_stock_purchase boolean not null default false,
  -- SET NULL: deleting a stock item must never destroy the money record. The
  -- purchase expense (or sale income) stays; only the link is cleared.
  stock_item_id     uuid references public.stock_items (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- now that transactions exists, wire the reverse FK on stock_items.
-- SET NULL: if the source purchase transaction is deleted, the stock item
-- survives as standalone inventory and just loses the back-link.
do $$ begin
  alter table public.stock_items
    add constraint stock_items_source_transaction_fk
    foreign key (source_transaction_id)
    references public.transactions (id) on delete set null;
exception when duplicate_object then null; end $$;

-- ===========================================================================
-- stock_sales — links an income transaction to the item sold + realised profit
-- ===========================================================================
create table if not exists public.stock_sales (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- RESTRICT: an item with sales history (realised profit) cannot be deleted —
  -- that would corrupt profit reporting. Delete the sale first (which the app
  -- treats as a reversal, restoring qty_remaining), or archive the item instead.
  stock_item_id       uuid not null references public.stock_items (id) on delete restrict,
  -- SET NULL: keep the sale record if its income transaction is removed; the
  -- app handles proper sale reversal (qty restore) explicitly.
  sale_transaction_id uuid references public.transactions (id) on delete set null,
  qty_sold            integer not null default 1 check (qty_sold > 0),
  sale_price          numeric(14, 2) not null default 0,        -- per unit
  -- profit = (sale_price - cost_per_unit) * qty_sold, computed by the app/RPC
  profit              numeric(14, 2) not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ===========================================================================
-- favorites — one-tap presets
-- ===========================================================================
create table if not exists public.favorites (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  label       text not null,
  amount      numeric(14, 2),
  type        public.transaction_type not null default 'expense',
  category_id uuid references public.categories (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ===========================================================================
-- recurring — scheduled auto entries
-- ===========================================================================
create table if not exists public.recurring (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  label       text not null,
  type        public.transaction_type not null default 'expense',
  amount      numeric(14, 2) not null default 0,
  category_id uuid references public.categories (id) on delete set null,
  wallet_id   uuid references public.wallets (id) on delete set null,
  schedule    text not null,               -- e.g. 'monthly:1', 'weekly:mon' (app-defined)
  next_run    date,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists wallets_user_idx        on public.wallets (user_id);
create index if not exists categories_user_idx     on public.categories (user_id);
create index if not exists transactions_user_date_idx on public.transactions (user_id, date desc);
create index if not exists transactions_category_idx  on public.transactions (category_id);
create index if not exists transactions_stock_item_idx on public.transactions (stock_item_id);
create index if not exists stock_items_user_status_idx on public.stock_items (user_id, status);
create index if not exists stock_items_needs_details_idx on public.stock_items (user_id) where needs_details;
create index if not exists stock_sales_item_idx    on public.stock_sales (stock_item_id);
create index if not exists stock_sales_user_idx    on public.stock_sales (user_id);
create index if not exists favorites_user_idx      on public.favorites (user_id);
create index if not exists recurring_user_idx      on public.recurring (user_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'wallets','categories','stock_items','transactions','stock_sales','favorites','recurring'
  ]
  loop
    execute format('drop trigger if exists set_updated_at on public.%I;', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
       for each row execute function public.set_updated_at();', t);
  end loop;
end $$;

-- ===========================================================================
-- Row Level Security — enable + owner-only policies on EVERY table.
-- (RLS is likely already enabled by automatic RLS; enabling again is a no-op.)
-- Policies scope every row to its owner via auth.uid() = user_id, and are
-- granted only to the `authenticated` role (anon has no access).
-- ===========================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'wallets','categories','stock_items','transactions','stock_sales','favorites','recurring'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists %1$I on public.%2$I;', t || '_select_own', t);
    execute format(
      'create policy %1$I on public.%2$I for select to authenticated
         using (auth.uid() = user_id);', t || '_select_own', t);

    execute format('drop policy if exists %1$I on public.%2$I;', t || '_insert_own', t);
    execute format(
      'create policy %1$I on public.%2$I for insert to authenticated
         with check (auth.uid() = user_id);', t || '_insert_own', t);

    execute format('drop policy if exists %1$I on public.%2$I;', t || '_update_own', t);
    execute format(
      'create policy %1$I on public.%2$I for update to authenticated
         using (auth.uid() = user_id) with check (auth.uid() = user_id);', t || '_update_own', t);

    execute format('drop policy if exists %1$I on public.%2$I;', t || '_delete_own', t);
    execute format(
      'create policy %1$I on public.%2$I for delete to authenticated
         using (auth.uid() = user_id);', t || '_delete_own', t);
  end loop;
end $$;
